### ISSUE TITLE
Able to create appointment before Patient DOB

### ISSUE THREAD

**Issue by limrik** [AY2324S2-CS2103T-F10-3/tp#101]
<img width="1458" alt="Screenshot 2024-04-03 at 4 27 03 PM" src="https://github.com/AY2324S2-CS2103T-F10-3/tp/assets/64995992/c598f88a-bd2d-4e28-9174-e1cbc519a6fa">

Was wondering if it made sense that appointments are even able to be created for dates that have already passed, do we want to limit this to dates from the current date onwards?

**Comment by ThatGirlJam** [comment]
Hmm it wouldn't be common to create appointments for dates that have already passed, but it could also be possible that the patient had a walk-in appt and the clinic staff forgot to put it in the record on that day itself? 

It would definitely be reasonable to limit the creation for dates to be after current date / DOB though
