### ISSUE TITLE
Unable to read Type and Note given extremely long input

### ISSUE THREAD

**Issue by limrik** [AY2324S2-CS2103T-F10-3/tp#102]
<img width="1460" alt="Screenshot 2024-04-03 at 4 44 16 PM" src="https://github.com/AY2324S2-CS2103T-F10-3/tp/assets/64995992/0ed33aa1-edf9-4a2d-be73-dd206507b1d3">

As we have no way to get the entire string for appointment type and notes, shall we limit the number of characters so that it shows up properly in the UI?

**Comment by xuelinglow** [comment]
I think maybe for tags should limit but i think notes wise maybe can find a way to wrap the text inside the container? Or both can wrap text so no need to limit number of characters, though tag wise might look ugly 
![Screenshot 2024-04-04 042028](https://github.com/AY2324S2-CS2103T-F10-3/tp/assets/56527991/5e9ad5e2-93f4-45c9-aad9-1f21e50677c8)
^ tried with  Label wrapText="true" just to see how it looks like
