### ISSUE TITLE
Patient Name field not allowing special characters

### ISSUE THREAD

**Issue by limrik** [AY2324S2-CS2103T-F10-3/tp#103]
<img width="1065" alt="Screenshot 2024-04-03 at 4 59 01 PM" src="https://github.com/AY2324S2-CS2103T-F10-3/tp/assets/64995992/ab6e17c4-18b6-4e9f-9385-2ec9a25473ab">
 
<img width="1010" alt="Screenshot 2024-04-03 at 4 59 34 PM" src="https://github.com/AY2324S2-CS2103T-F10-3/tp/assets/64995992/b000e1e4-d018-4ae1-b1ae-99a5934a6601">

<img width="964" alt="Screenshot 2024-04-03 at 5 00 04 PM" src="https://github.com/AY2324S2-CS2103T-F10-3/tp/assets/64995992/cc1cfe13-abf6-44b1-8e42-6d4f9996b610">

Perhaps name field should allow for more diversity?

**Comment by dayn-1** [comment]
Update in UG to state only English alphanumeric characters allowed. This prevents further misuse such as having "@@@@' as a patient name.
