### ISSUE TITLE
[PE-D][Tester D] docs: Day-View and Overall-View is not elaborated upon in the user guide.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F10-3/tp#124]
Upon searching through the user guide, I am unable to find any section relating to the Day-View and Overall-View features of the application beyond the initial labelling in the screenshot of the quick start section. The lack of documentation prevents me from utilising the feature.

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: delishad21/ped#3

**Comment by dayn-1** [comment]
Must fix.

Updated in latest UG updates.
