### ISSUE TITLE
[PE-D][Tester E] Names do not allow the '/' character

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F10-3/tp#132]
![image.png](https://raw.githubusercontent.com/jimseah-0116/ped/main/files/7eadff43-7ce5-4c33-8438-6759d66f00bb.png)

Tried to key in a name "Testing s/o testname".
User guide does mention that names can only contain "English alphanumeric characters", but s/o and d/o are commonly found in patronymic full names. Might affect usage for target users.

Command to reproduce:
addPatient i/T0101049F n/Testing s/o testname p/95551234 e/test@test b/1998-04-06 a/test street

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: jimseah-0116/ped#3

**Comment by dayn-1** [comment]
Similar issue as raised in #135
