### ISSUE TITLE
[PE-D][Tester D] Limited character count for addresses

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F10-3/tp#134]
Character count for addresses is too low. There are local examples that the app cannot accomodate. With foreign addresses, you might have to consider character count of state names as well. 60 characters is definitely not sufficient.

Example: Block 268B, Chua Chu Kang Avenue 3, #05-492, Singapore 642268

![image.png](https://raw.githubusercontent.com/delishad21/ped/main/files/3c48f8dd-57d6-466d-a60d-ddd1fc900d00.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: delishad21/ped#6

**Comment by dayn-1** [comment]
Won't Fix. Constraint was put in place to prevent misuse of inputting extreme numbers of characters.
Example given could be shortened to Blk 268B Choa Chu Kang Ave 3 #05-492 S(642268) without losing any information.

Nevertheless, this was added into plans for future enhancements by @ThatGirlJam to support more characters.
