### ISSUE TITLE
[PE-D][Tester E] NRIC field must start and end with capital letters

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F10-3/tp#147]
All commands that require an NRIC field will only allow NRIC input with capital letters.

Would be good to allow lower-case letters for NRIC as well, to make it more user-friendly

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: jimseah-0116/ped#5

**Comment by dayn-1** [comment]
Not allowed to fix in v1.4 as it results in change in behaviour.
Updated by @ThatGirlJam to include this in plans for future enhancements.
