### ISSUE TITLE
[PE-D][Tester C] Use of visuals for adding an appointment

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F10-3/tp#150]
![Screenshot 2024-04-05 at 5.29.55 PM.png](https://raw.githubusercontent.com/SherwynNg/ped/main/files/9ca4e9b0-4779-4995-ac30-e53c9417cdc3.png)

Expected:
Thought that it will be nice to include a screenshot to show where the appointment will be added.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: SherwynNg/ped#10

**Comment by dayn-1** [comment]
Good to fix.

Screenshots were included in UG in the latest updates.
