### ISSUE TITLE
[PE-D][Tester C] UG didn't state clear requirement for editing appointment

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F10-3/tp#153]
![Screenshot 2024-04-05 at 5.47.22 PM.png](https://raw.githubusercontent.com/SherwynNg/ped/main/files/14e20647-adb7-4697-858d-6ac9cc3e5574.png)

1. Navigate to section "Editing an Appointment

The UG state to provide at least one optional field for editing. But after specifying only the newfrom field, there is no actions or error carried out.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: SherwynNg/ped#13

**Comment by dayn-1** [comment]
Describes same issues surfaced in #168
