### ISSUE TITLE
[PE-D][Tester E] Long tags get cut out in the Patients panel view

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F10-3/tp#154]
If a user inputs a very long tag and resizes the app window to the minimum size, long tags get cut off from the UI. There is no scroll-bar for users to see the full tag. In this example, the tag is cut:

Window size set to the minimum:

![image.png](https://raw.githubusercontent.com/jimseah-0116/ped/main/files/cb128b5c-14ba-4af4-896d-c5772b4f127c.png)

Window size made bigger:

![image.png](https://raw.githubusercontent.com/jimseah-0116/ped/main/files/f1ab0563-14eb-4083-b122-064cd59e82ae.png)

To reproduce problem, add a patient with tag: "AAA....AA" (29 As)
Consider making the minWidth and minHeight of the main window bigger, or adding a scrollbar on each PersonCard in the Patients panel.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: jimseah-0116/ped#6

**Comment by dayn-1** [comment]
Not allowed to fix in v1.4.
