### ISSUE TITLE
[PE-D][Tester E] Make it easier to determine the appointment date and time

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F10-3/tp#159]
When looking at the whole main window, it is not easy to determine appointment date and time (for both overall-view and day-view). Would be good to make the appointment date and time **BOLD or bigger**.

![image.png](https://raw.githubusercontent.com/jimseah-0116/ped/main/files/58387de6-be54-4169-89c1-662318a8826c.png)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: jimseah-0116/ped#8

**Comment by dayn-1** [comment]
Not allowed to fix in v1.4.
