### ISSUE TITLE
[PE-D][Tester E] Links in UG not working

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F10-3/tp#161]
These two links do not work:

Link at 'here', top of page 6:

![image.png](https://raw.githubusercontent.com/jimseah-0116/ped/main/files/05d7d120-807c-46ee-a1e3-6adbeecc18ed.png)

Link at 'here', middle of page 6:

![image.png](https://raw.githubusercontent.com/jimseah-0116/ped/main/files/277aafe8-302f-40fc-a6c1-7fb11235ece5.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: jimseah-0116/ped#9

**Comment by dayn-1** [comment]
Must fix.

Ensured working hyper links in latest UG updates.
