### ISSUE TITLE
[PE-D][Tester E] Appointment colours documentation

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F10-3/tp#164]
Image taken from user guide:

![image.png](https://raw.githubusercontent.com/jimseah-0116/ped/main/files/16460423-41a3-4784-8eb8-0210fb9e5c02.png)

Green and red appointments are labelled, but the cream-white appointments are not explained. Consider explaining what this colour indicates as well.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: jimseah-0116/ped#11

**Comment by dayn-1** [comment]
Must fix to prevent confusion.

Updated in latest UG updates.
