### ISSUE TITLE
[PE-D][Tester D] User Guide document name contains reference to AB3

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F10-3/tp#171]
![image.png](https://raw.githubusercontent.com/delishad21/ped/main/files/842bad0d-d381-4bb1-9a29-a92fdb3dc835.png)

At the top of every page in the user guide, there is a reference to Address-Book-3, which is likely not intended since this product is quite far detached from being just a general addressbook

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: delishad21/ped#17

**Comment by dayn-1** [comment]
Good to fix.

Updated in latest UG updates.
