### ISSUE TITLE
As a user, I can add new patient’s information to the database.

### ISSUE THREAD

**Issue by cliftonchee** [AY2324S2-CS2103T-F10-3/tp#22]

**Comment by ThatGirlJam** [comment]
Hi rik! Thanks for completing the feature, although the new information is recorded down it doesn't seem to appear in the addressbook when running the GUI on my end 😅 Was wondering if this is the same on your side?

**Comment by limrik** [comment]
Hi @ThatGirlJam, right now you can see the information in `addressbook.json` but not on the GUI yet, will look to update that in v1.2b!
